name: .NET Test Automation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest
      
    - name: Restore dependencies
      run: dotnet restore ./HudlTestProject/HudlTestProject.csproj
      
    - name: Build
      run: dotnet build ./HudlTestProject/HudlTestProject.csproj --no-restore
      
    - name: Create Test Credentials
      run: |
        mkdir -p ./HudlTestProject/HudlTestProject/Utils
        echo '{"ValidUsername":"${{ secrets.HUDL_USERNAME }}","ValidPassword":"${{ secrets.HUDL_PASSWORD }}","InvalidPassword":"wrongPassword","InvalidEmail":"invalid","TestUsername":"test@example.com"}' > ./HudlTestProject/HudlTestProject/Utils/TestCredentials.json
      
    - name: Run Tests
      run: dotnet test ./HudlTestProject/HudlTestProject.csproj --no-build --verbosity normal --logger trx --results-directory TestResults
      
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/*.trx